In [60]:
import pandas as pd
#data from data.cityofnewyork.us
cs_schools=pd.read_csv('2017-2018_Computer_Science_Report_LL177.csv')
cs_schools.head()

,Category Type,Category Values,# of Students All Grades,# Students Taking CS All Grades,% Students Taking CS (Citywide) All Grades,% Within CS All Grades,# of Students Grades K-5,# Students Taking CS Grades K-5,% Students Taking CS (Citywide) Grades 6-8,% Within CS Grades K-5,# of Students Grades 6-8,# Students Taking CS Grades 6-8,% Students Taking CS (Citywide) Grades 6-8 1,% Within CS Grades 6-8,# of Students Grades 6-8 1,# Students Taking CS Grades 6-8 1,% Students Taking CS (Citywide) Grades 6-8 2,% Within CS Grades 6-8 1
0,District,01,11088,1241,11.2,0.9,5175,347,6.7,0.5,2468,310,12.6,1.0,3445,584,17.0,2.2
1,District,02,61641,7270,11.8,5.4,17856,2670,15.0,3.5,8002,498,6.2,1.6,35783,4102,11.5,15.7
2,District,03,21770,1695,7.8,1.3,8508,730,8.6,1.0,4336,517,11.9,1.6,8926,448,5.0,1.7
3,District,04,12618,866,6.9,0.6,5920,204,3.4,0.3,2982,364,12.2,1.1,3716,298,8.0,1.1
4,District,05,10791,963,8.9,0.7,4759,574,12.1,0.7,2360,185,7.8,0.6,3672,204,5.6,0.8

In [61]:
cs_schools.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 18 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Category Type                                 53 non-null     object
 1   Category Values                               52 non-null     object
 2   # of Students All Grades                      53 non-null     int64
 3   # Students Taking CS All Grades               53 non-null     int64
 4   % Students Taking CS (Citywide) All Grades    53 non-null     float64
 5   % Within CS All Grades                        53 non-null     float64
 6   # of Students Grades K-5                      53 non-null     int64
 7   # Students Taking CS Grades K-5               53 non-null     int64
 8   % Students Taking CS (Citywide) Grades 6-8    53 non-null     float64
 9   % Within CS Grades K-5                        53 non-null     float64
 10  # of Students Grades 6-8                      53 non-null     int64
 11  # Students Taking CS Grades 6-8               53 non-null     object
 12  % Students Taking CS (Citywide) Grades 6-8 1  53 non-null     object
 13  % Within CS Grades 6-8                        53 non-null     object
 14  # of Students Grades 6-8 1                    53 non-null     int64
 15  # Students Taking CS Grades 6-8 1             53 non-null     int64
 16  % Students Taking CS (Citywide) Grades 6-8 2  53 non-null     float64
 17  % Within CS Grades 6-8 1                      53 non-null     float64
dtypes: float64(6), int64(7), object(5)
memory usage: 7.6+ KB

In [62]:
cs_schools['Category Type'].value_counts()

District                           33
Ethnicity                           6
Borough                             5
Economic Disadvantaged Status       2
English Language Learner Status     2
Gender                              2
Student with Disability Status      2
Total                               1
Name: Category Type, dtype: int64

In [63]:
cs_schools['Category Values'].value_counts()

01                               1
02                               1
29                               1
30                               1
31                               1
32                               1
75                               1
Bronx                            1
Brooklyn                         1
Manhattan                        1
Queens                           1
Staten Island                    1
Economic Disadvantaged           1
Non Economic Disadvantaged       1
English Language Learners        1
Non English Language Learners    1
Asian                            1
Black                            1
Hispanic                         1
Multi-Racial                     1
Native American                  1
White                            1
Female                           1
Male                             1
Students with Disabilities       1
28                               1
27                               1
26                               1
13                               1
03                               1
04                               1
05                               1
06                               1
07                               1
08                               1
09                               1
10                               1
11                               1
12                               1
14                               1
25                               1
15                               1
16                               1
17                               1
18                               1
19                               1
20                               1
21                               1
22                               1
23                               1
24                               1
Students without Disabilities    1
Name: Category Values, dtype: int64

In [64]:
totmask=cs_schools['Category Type']=='Total'
cs_schools[totmask]

,Category Type,Category Values,# of Students All Grades,# Students Taking CS All Grades,% Students Taking CS (Citywide) All Grades,% Within CS All Grades,# of Students Grades K-5,# Students Taking CS Grades K-5,% Students Taking CS (Citywide) Grades 6-8,% Within CS Grades K-5,# of Students Grades 6-8,# Students Taking CS Grades 6-8,% Students Taking CS (Citywide) Grades 6-8 1,% Within CS Grades 6-8,# of Students Grades 6-8 1,# Students Taking CS Grades 6-8 1,% Students Taking CS (Citywide) Grades 6-8 2,% Within CS Grades 6-8 1
52,Total,NaN,963973,134507,14.0,100.0,446271,76699,17.2,100.0,211213,"31,703",15.0,100.0,306489,26105,8.5,100.0

In [65]:
#Headings are clearly wrong.  If I wasn't doing this for an educational project I would need to contact the City Schools 
#to make sure I put the correct data in the correct places.
#The first "% Students Taking CS (Citywide) Grades 6-8" has the correct % for K-5.  The last columns that repeat
# Grades 6-8 I will assume are 9-12.  I will also replace 'Within CS' with 'of ALL CS' .
col_map={
    '% Within CS All Grades':'% of All CS, All Grades',
    '% Students Taking CS (Citywide) Grades 6-8':'% Students Taking CS (Citywide) Grades K-5',
    '% Within CS Grades K-5':'% of All CS, Grades K-5',
    '% Students Taking CS (Citywide) Grades 6-8 1':'% Students Taking CS (Citywide) Grades 6-8',
    '% Within CS Grades 6-8':'% of All CS, Grades 6-8',
    '# of Students Grades 6-8 1':'# of Students Grades 9-12',
    '# Students Taking CS Grades 6-8 1':'# Students Taking CS Grades 9-12',
    '% Students Taking CS (Citywide) Grades 6-8 2':'% Students Taking CS (Citywide) Grades 9-12',
    '% Within CS Grades 6-8 1':'% of All CS, Grades 9-12'
}
cs_schools=cs_schools.rename(mapper=col_map, axis=1)
cs_schools.head()

,Category Type,Category Values,# of Students All Grades,# Students Taking CS All Grades,% Students Taking CS (Citywide) All Grades,"% of All CS, All Grades",# of Students Grades K-5,# Students Taking CS Grades K-5,% Students Taking CS (Citywide) Grades K-5,"% of All CS, Grades K-5",# of Students Grades 6-8,# Students Taking CS Grades 6-8,% Students Taking CS (Citywide) Grades 6-8,"% of All CS, Grades 6-8",# of Students Grades 9-12,# Students Taking CS Grades 9-12,% Students Taking CS (Citywide) Grades 9-12,"% of All CS, Grades 9-12"
0,District,01,11088,1241,11.2,0.9,5175,347,6.7,0.5,2468,310,12.6,1.0,3445,584,17.0,2.2
1,District,02,61641,7270,11.8,5.4,17856,2670,15.0,3.5,8002,498,6.2,1.6,35783,4102,11.5,15.7
2,District,03,21770,1695,7.8,1.3,8508,730,8.6,1.0,4336,517,11.9,1.6,8926,448,5.0,1.7
3,District,04,12618,866,6.9,0.6,5920,204,3.4,0.3,2982,364,12.2,1.1,3716,298,8.0,1.1
4,District,05,10791,963,8.9,0.7,4759,574,12.1,0.7,2360,185,7.8,0.6,3672,204,5.6,0.8

In [66]:
#checking to see if % are correct in '% Students Taking CS (Citywide) Grades K-5' (Would do in all cols if a job.)
per_mask=cs_schools['% Students Taking CS (Citywide) Grades K-5']!=round(100*cs_schools['# Students Taking CS Grades K-5']/cs_schools['# of Students Grades K-5'],1)
cs_schools[per_mask]

Empty DataFrame
Columns: [Category Type, Category Values, # of Students All Grades, # Students Taking CS All Grades, % Students Taking CS (Citywide) All Grades, % of All CS, All Grades, # of Students Grades K-5, # Students Taking CS Grades K-5, % Students Taking CS (Citywide) Grades K-5, % of All CS, Grades K-5, # of Students Grades 6-8, # Students Taking CS Grades 6-8, % Students Taking CS (Citywide) Grades 6-8, % of All CS, Grades 6-8, # of Students Grades 9-12, # Students Taking CS Grades 9-12, % Students Taking CS (Citywide) Grades 9-12, % of All CS, Grades 9-12]
Index: []

In [67]:
#Look at highest and lowest participation for all districts
district_mask=cs_schools['Category Type']=='District'
cs_schools[district_mask].sort_values(by='% Students Taking CS (Citywide) All Grades')

,Category Type,Category Values,# of Students All Grades,# Students Taking CS All Grades,% Students Taking CS (Citywide) All Grades,"% of All CS, All Grades",# of Students Grades K-5,# Students Taking CS Grades K-5,% Students Taking CS (Citywide) Grades K-5,"% of All CS, Grades K-5",# of Students Grades 6-8,# Students Taking CS Grades 6-8,% Students Taking CS (Citywide) Grades 6-8,"% of All CS, Grades 6-8",# of Students Grades 9-12,# Students Taking CS Grades 9-12,% Students Taking CS (Citywide) Grades 9-12,"% of All CS, Grades 9-12"
11,District,12,22656,628,2.8,0.5,11225,12,0.1,0.0,5100,97,1.9,0.3,6331,519,8.2,2.0
32,District,75,26275,1035,3.9,0.8,11321,374,3.3,0.5,5078,274,5.4,0.9,9876,387,3.9,1.5
10,District,11,38391,1661,4.3,1.2,19915,748,3.8,1.0,9433,810,8.6,2.6,9043,103,1.1,0.4
6,District,07,18401,826,4.5,0.6,7690,24,0.3,0.0,3528,293,8.3,0.9,7183,509,7.1,1.9
7,District,08,27318,1502,5.5,1.1,13214,539,4.1,0.7,6404,676,10.6,2.1,7700,287,3.7,1.1
22,District,23,8694,498,5.7,0.4,4360,300,6.9,0.4,2679,148,5.5,0.5,1655,50,3.0,0.2
3,District,04,12618,866,6.9,0.6,5920,204,3.4,0.3,2982,364,12.2,1.1,3716,298,8.0,1.1
5,District,06,21354,1513,7.1,1.1,10707,756,7.1,1.0,5006,573,11.4,1.8,5641,184,3.3,0.7
2,District,03,21770,1695,7.8,1.3,8508,730,8.6,1.0,4336,517,11.9,1.6,8926,448,5.0,1.7
31,District,32,10662,855,8.0,0.6,5059,223,4.4,0.3,3183,456,14.3,1.4,2420,176,7.3,0.7
8,District,09,33388,2858,8.6,2.1,16884,1590,9.4,2.1,8228,705,8.6,2.2,8276,563,6.8,2.2
4,District,05,10791,963,8.9,0.7,4759,574,12.1,0.7,2360,185,7.8,0.6,3672,204,5.6,0.8
9,District,10,53991,5435,10.1,4.0,26022,3647,14.0,4.8,11803,962,8.2,3.0,16166,826,5.1,3.2
20,District,21,34798,3569,10.3,2.7,13745,867,6.3,1.1,9327,"1,566",16.8,4.9,11726,1136,9.7,4.4
0,District,01,11088,1241,11.2,0.9,5175,347,6.7,0.5,2468,310,12.6,1.0,3445,584,17.0,2.2
16,District,17,20938,2448,11.7,1.8,8574,1898,22.1,2.5,4686,s,s,s,7678,550,7.2,2.1
1,District,02,61641,7270,11.8,5.4,17856,2670,15.0,3.5,8002,498,6.2,1.6,35783,4102,11.5,15.7
14,District,15,30697,3827,12.5,2.8,18501,2137,11.6,2.8,6027,"1,427",23.7,4.5,6169,263,4.3,1.0
18,District,19,21512,2723,12.7,2.0,10819,1399,12.9,1.8,5095,"1,068",21.0,3.4,5598,256,4.6,1.0
13,District,14,17619,2669,15.1,2.0,7543,1742,23.1,2.3,3638,343,9.4,1.1,6438,584,9.1,2.2
23,District,24,57548,8871,15.4,6.6,29851,5413,18.1,7.1,13350,"2,102",15.7,6.6,14347,1356,9.5,5.2
29,District,30,38548,6073,15.8,4.5,18383,3138,17.1,4.1,9873,"2,322",23.5,7.3,10292,613,6.0,2.3
15,District,16,6325,1013,16.0,0.8,3209,825,25.7,1.1,1006,s,s,s,2110,127,6.0,0.5
28,District,29,26026,4247,16.3,3.2,14534,3078,21.2,4.0,6946,403,5.8,1.3,4546,766,16.8,2.9
12,District,13,20560,3434,16.7,2.6,6756,625,9.3,0.8,2089,316,15.1,1.0,11715,2493,21.3,9.5
27,District,28,40184,7059,17.6,5.2,17235,4361,25.3,5.7,7846,"2,093",26.7,6.6,15103,605,4.0,2.3
17,District,18,14766,2630,17.8,2.0,6885,1215,17.6,1.6,3344,771,23.1,2.4,4537,644,14.2,2.5
19,District,20,50896,9236,18.1,6.9,25355,6399,25.2,8.3,12339,"1,756",14.2,5.5,13202,1081,8.2,4.1
21,District,22,33418,6112,18.3,4.5,16990,2555,15.0,3.3,6413,"2,211",34.5,7.0,10015,1346,13.4,5.2
26,District,27,42997,8460,19.7,6.3,21515,6212,28.9,8.1,10963,"1,336",12.2,4.2,10519,912,8.7,3.5
30,District,31,59364,12658,21.3,9.4,28177,7095,25.2,9.3,13005,"4,017",30.9,12.7,18182,1546,8.5,5.9
24,District,25,37139,9563,25.7,7.1,18052,7594,42.1,9.9,8570,572,6.7,1.8,10517,1397,13.3,5.4
25,District,26,31600,11069,35.0,8.2,11532,7408,64.2,9.7,6106,"2,471",40.5,7.8,13962,1190,8.5,4.6

In [68]:
#Are the highest and lowest participation for all districts the same throughout grade level?

cs_schools[district_mask].sort_values(by='% Students Taking CS (Citywide) Grades K-5')

,Category Type,Category Values,# of Students All Grades,# Students Taking CS All Grades,% Students Taking CS (Citywide) All Grades,"% of All CS, All Grades",# of Students Grades K-5,# Students Taking CS Grades K-5,% Students Taking CS (Citywide) Grades K-5,"% of All CS, Grades K-5",# of Students Grades 6-8,# Students Taking CS Grades 6-8,% Students Taking CS (Citywide) Grades 6-8,"% of All CS, Grades 6-8",# of Students Grades 9-12,# Students Taking CS Grades 9-12,% Students Taking CS (Citywide) Grades 9-12,"% of All CS, Grades 9-12"
11,District,12,22656,628,2.8,0.5,11225,12,0.1,0.0,5100,97,1.9,0.3,6331,519,8.2,2.0
6,District,07,18401,826,4.5,0.6,7690,24,0.3,0.0,3528,293,8.3,0.9,7183,509,7.1,1.9
32,District,75,26275,1035,3.9,0.8,11321,374,3.3,0.5,5078,274,5.4,0.9,9876,387,3.9,1.5
3,District,04,12618,866,6.9,0.6,5920,204,3.4,0.3,2982,364,12.2,1.1,3716,298,8.0,1.1
10,District,11,38391,1661,4.3,1.2,19915,748,3.8,1.0,9433,810,8.6,2.6,9043,103,1.1,0.4
7,District,08,27318,1502,5.5,1.1,13214,539,4.1,0.7,6404,676,10.6,2.1,7700,287,3.7,1.1
31,District,32,10662,855,8.0,0.6,5059,223,4.4,0.3,3183,456,14.3,1.4,2420,176,7.3,0.7
20,District,21,34798,3569,10.3,2.7,13745,867,6.3,1.1,9327,"1,566",16.8,4.9,11726,1136,9.7,4.4
0,District,01,11088,1241,11.2,0.9,5175,347,6.7,0.5,2468,310,12.6,1.0,3445,584,17.0,2.2
22,District,23,8694,498,5.7,0.4,4360,300,6.9,0.4,2679,148,5.5,0.5,1655,50,3.0,0.2
5,District,06,21354,1513,7.1,1.1,10707,756,7.1,1.0,5006,573,11.4,1.8,5641,184,3.3,0.7
2,District,03,21770,1695,7.8,1.3,8508,730,8.6,1.0,4336,517,11.9,1.6,8926,448,5.0,1.7
12,District,13,20560,3434,16.7,2.6,6756,625,9.3,0.8,2089,316,15.1,1.0,11715,2493,21.3,9.5
8,District,09,33388,2858,8.6,2.1,16884,1590,9.4,2.1,8228,705,8.6,2.2,8276,563,6.8,2.2
14,District,15,30697,3827,12.5,2.8,18501,2137,11.6,2.8,6027,"1,427",23.7,4.5,6169,263,4.3,1.0
4,District,05,10791,963,8.9,0.7,4759,574,12.1,0.7,2360,185,7.8,0.6,3672,204,5.6,0.8
18,District,19,21512,2723,12.7,2.0,10819,1399,12.9,1.8,5095,"1,068",21.0,3.4,5598,256,4.6,1.0
9,District,10,53991,5435,10.1,4.0,26022,3647,14.0,4.8,11803,962,8.2,3.0,16166,826,5.1,3.2
21,District,22,33418,6112,18.3,4.5,16990,2555,15.0,3.3,6413,"2,211",34.5,7.0,10015,1346,13.4,5.2
1,District,02,61641,7270,11.8,5.4,17856,2670,15.0,3.5,8002,498,6.2,1.6,35783,4102,11.5,15.7
29,District,30,38548,6073,15.8,4.5,18383,3138,17.1,4.1,9873,"2,322",23.5,7.3,10292,613,6.0,2.3
17,District,18,14766,2630,17.8,2.0,6885,1215,17.6,1.6,3344,771,23.1,2.4,4537,644,14.2,2.5
23,District,24,57548,8871,15.4,6.6,29851,5413,18.1,7.1,13350,"2,102",15.7,6.6,14347,1356,9.5,5.2
28,District,29,26026,4247,16.3,3.2,14534,3078,21.2,4.0,6946,403,5.8,1.3,4546,766,16.8,2.9
16,District,17,20938,2448,11.7,1.8,8574,1898,22.1,2.5,4686,s,s,s,7678,550,7.2,2.1
13,District,14,17619,2669,15.1,2.0,7543,1742,23.1,2.3,3638,343,9.4,1.1,6438,584,9.1,2.2
30,District,31,59364,12658,21.3,9.4,28177,7095,25.2,9.3,13005,"4,017",30.9,12.7,18182,1546,8.5,5.9
19,District,20,50896,9236,18.1,6.9,25355,6399,25.2,8.3,12339,"1,756",14.2,5.5,13202,1081,8.2,4.1
27,District,28,40184,7059,17.6,5.2,17235,4361,25.3,5.7,7846,"2,093",26.7,6.6,15103,605,4.0,2.3
15,District,16,6325,1013,16.0,0.8,3209,825,25.7,1.1,1006,s,s,s,2110,127,6.0,0.5
26,District,27,42997,8460,19.7,6.3,21515,6212,28.9,8.1,10963,"1,336",12.2,4.2,10519,912,8.7,3.5
24,District,25,37139,9563,25.7,7.1,18052,7594,42.1,9.9,8570,572,6.7,1.8,10517,1397,13.3,5.4
25,District,26,31600,11069,35.0,8.2,11532,7408,64.2,9.7,6106,"2,471",40.5,7.8,13962,1190,8.5,4.6

In [69]:
#The low in K-5 similar to low in ALL.  However in High, District 16 has a larger % of K-5 
#District 26 has very high K-5 participation but that steadily decreases by 9-12
#Look at general trend through Districts
cs_schools['% part 9-12 - % part k-5']=cs_schools['% Students Taking CS (Citywide) Grades 9-12']-cs_schools['% Students Taking CS (Citywide) Grades K-5']
cs_schools[district_mask].sort_values(by='% part 9-12 - % part k-5')

,Category Type,Category Values,# of Students All Grades,# Students Taking CS All Grades,% Students Taking CS (Citywide) All Grades,"% of All CS, All Grades",# of Students Grades K-5,# Students Taking CS Grades K-5,% Students Taking CS (Citywide) Grades K-5,"% of All CS, Grades K-5",# of Students Grades 6-8,# Students Taking CS Grades 6-8,% Students Taking CS (Citywide) Grades 6-8,"% of All CS, Grades 6-8",# of Students Grades 9-12,# Students Taking CS Grades 9-12,% Students Taking CS (Citywide) Grades 9-12,"% of All CS, Grades 9-12",% part 9-12 - % part k-5
25,District,26,31600,11069,35.0,8.2,11532,7408,64.2,9.7,6106,"2,471",40.5,7.8,13962,1190,8.5,4.6,-55.7
24,District,25,37139,9563,25.7,7.1,18052,7594,42.1,9.9,8570,572,6.7,1.8,10517,1397,13.3,5.4,-28.8
27,District,28,40184,7059,17.6,5.2,17235,4361,25.3,5.7,7846,"2,093",26.7,6.6,15103,605,4.0,2.3,-21.3
26,District,27,42997,8460,19.7,6.3,21515,6212,28.9,8.1,10963,"1,336",12.2,4.2,10519,912,8.7,3.5,-20.2
15,District,16,6325,1013,16.0,0.8,3209,825,25.7,1.1,1006,s,s,s,2110,127,6.0,0.5,-19.7
19,District,20,50896,9236,18.1,6.9,25355,6399,25.2,8.3,12339,"1,756",14.2,5.5,13202,1081,8.2,4.1,-17.0
30,District,31,59364,12658,21.3,9.4,28177,7095,25.2,9.3,13005,"4,017",30.9,12.7,18182,1546,8.5,5.9,-16.7
16,District,17,20938,2448,11.7,1.8,8574,1898,22.1,2.5,4686,s,s,s,7678,550,7.2,2.1,-14.9
13,District,14,17619,2669,15.1,2.0,7543,1742,23.1,2.3,3638,343,9.4,1.1,6438,584,9.1,2.2,-14.0
29,District,30,38548,6073,15.8,4.5,18383,3138,17.1,4.1,9873,"2,322",23.5,7.3,10292,613,6.0,2.3,-11.1
9,District,10,53991,5435,10.1,4.0,26022,3647,14.0,4.8,11803,962,8.2,3.0,16166,826,5.1,3.2,-8.9
23,District,24,57548,8871,15.4,6.6,29851,5413,18.1,7.1,13350,"2,102",15.7,6.6,14347,1356,9.5,5.2,-8.6
18,District,19,21512,2723,12.7,2.0,10819,1399,12.9,1.8,5095,"1,068",21.0,3.4,5598,256,4.6,1.0,-8.3
14,District,15,30697,3827,12.5,2.8,18501,2137,11.6,2.8,6027,"1,427",23.7,4.5,6169,263,4.3,1.0,-7.3
4,District,05,10791,963,8.9,0.7,4759,574,12.1,0.7,2360,185,7.8,0.6,3672,204,5.6,0.8,-6.5
28,District,29,26026,4247,16.3,3.2,14534,3078,21.2,4.0,6946,403,5.8,1.3,4546,766,16.8,2.9,-4.4
22,District,23,8694,498,5.7,0.4,4360,300,6.9,0.4,2679,148,5.5,0.5,1655,50,3.0,0.2,-3.9
5,District,06,21354,1513,7.1,1.1,10707,756,7.1,1.0,5006,573,11.4,1.8,5641,184,3.3,0.7,-3.8
2,District,03,21770,1695,7.8,1.3,8508,730,8.6,1.0,4336,517,11.9,1.6,8926,448,5.0,1.7,-3.6
1,District,02,61641,7270,11.8,5.4,17856,2670,15.0,3.5,8002,498,6.2,1.6,35783,4102,11.5,15.7,-3.5
17,District,18,14766,2630,17.8,2.0,6885,1215,17.6,1.6,3344,771,23.1,2.4,4537,644,14.2,2.5,-3.4
10,District,11,38391,1661,4.3,1.2,19915,748,3.8,1.0,9433,810,8.6,2.6,9043,103,1.1,0.4,-2.7
8,District,09,33388,2858,8.6,2.1,16884,1590,9.4,2.1,8228,705,8.6,2.2,8276,563,6.8,2.2,-2.6
21,District,22,33418,6112,18.3,4.5,16990,2555,15.0,3.3,6413,"2,211",34.5,7.0,10015,1346,13.4,5.2,-1.6
7,District,08,27318,1502,5.5,1.1,13214,539,4.1,0.7,6404,676,10.6,2.1,7700,287,3.7,1.1,-0.4
32,District,75,26275,1035,3.9,0.8,11321,374,3.3,0.5,5078,274,5.4,0.9,9876,387,3.9,1.5,0.6
31,District,32,10662,855,8.0,0.6,5059,223,4.4,0.3,3183,456,14.3,1.4,2420,176,7.3,0.7,2.9
20,District,21,34798,3569,10.3,2.7,13745,867,6.3,1.1,9327,"1,566",16.8,4.9,11726,1136,9.7,4.4,3.4
3,District,04,12618,866,6.9,0.6,5920,204,3.4,0.3,2982,364,12.2,1.1,3716,298,8.0,1.1,4.6
6,District,07,18401,826,4.5,0.6,7690,24,0.3,0.0,3528,293,8.3,0.9,7183,509,7.1,1.9,6.8
11,District,12,22656,628,2.8,0.5,11225,12,0.1,0.0,5100,97,1.9,0.3,6331,519,8.2,2.0,8.1
0,District,01,11088,1241,11.2,0.9,5175,347,6.7,0.5,2468,310,12.6,1.0,3445,584,17.0,2.2,10.3
12,District,13,20560,3434,16.7,2.6,6756,625,9.3,0.8,2089,316,15.1,1.0,11715,2493,21.3,9.5,12.0

In [70]:
#Most Districts have higher % participation in K-5 than 9-12.  In 8 districts, the opposite is true. 
#Is this because computers aren't as available in those k-5 schools? Or is there a successful campaign in 9-12 to increase interest?
gender_mask=cs_schools['Category Type']=='Gender'
cs_schools[gender_mask]

,Category Type,Category Values,# of Students All Grades,# Students Taking CS All Grades,% Students Taking CS (Citywide) All Grades,"% of All CS, All Grades",# of Students Grades K-5,# Students Taking CS Grades K-5,% Students Taking CS (Citywide) Grades K-5,"% of All CS, Grades K-5",# of Students Grades 6-8,# Students Taking CS Grades 6-8,% Students Taking CS (Citywide) Grades 6-8,"% of All CS, Grades 6-8",# of Students Grades 9-12,# Students Taking CS Grades 9-12,% Students Taking CS (Citywide) Grades 9-12,"% of All CS, Grades 9-12",% part 9-12 - % part k-5
48,Gender,Female,464681,63002,13.6,46.8,215016,37513,17.4,48.9,101952,"15,064",14.8,47.5,147713,10425,7.1,39.9,-10.3
49,Gender,Male,499292,71505,14.3,53.2,231255,39186,16.9,51.1,109261,"16,639",15.2,52.5,158776,15680,9.9,60.1,-7.0

In [71]:
#Although both boys and girls decrease in % participation, girls are much worse.
ethnic_mask=cs_schools['Category Type']=='Ethnicity'
cs_schools[ethnic_mask]

,Category Type,Category Values,# of Students All Grades,# Students Taking CS All Grades,% Students Taking CS (Citywide) All Grades,"% of All CS, All Grades",# of Students Grades K-5,# Students Taking CS Grades K-5,% Students Taking CS (Citywide) Grades K-5,"% of All CS, Grades K-5",# of Students Grades 6-8,# Students Taking CS Grades 6-8,% Students Taking CS (Citywide) Grades 6-8,"% of All CS, Grades 6-8",# of Students Grades 9-12,# Students Taking CS Grades 9-12,% Students Taking CS (Citywide) Grades 9-12,"% of All CS, Grades 9-12",% part 9-12 - % part k-5
42,Ethnicity,Asian,170661,34253,20.1,25.5,80126,20424,25.5,26.6,37916,"6,696",17.7,21.1,52619,7133,13.6,27.3,-11.9
43,Ethnicity,Black,221735,24372,11.0,18.1,92057,13016,14.1,17.0,48315,"5,343",11.1,16.9,81363,6013,7.4,23.0,-6.7
44,Ethnicity,Hispanic,395134,45475,11.5,33.8,186195,25864,13.9,33.7,86961,"11,363",13.1,35.8,121978,8248,6.8,31.6,-7.1
45,Ethnicity,Multi-Racial,9468,1485,15.7,1.1,6472,1095,16.9,1.4,1536,229,14.9,0.7,1460,161,11.0,0.6,-5.9
46,Ethnicity,Native American,10457,1494,14.3,1.1,5104,947,18.6,1.2,2306,287,12.4,0.9,3047,260,8.5,1.0,-10.1
47,Ethnicity,White,152745,27078,17.7,20.1,76221,15345,20.1,20.0,33775,"7,728",22.9,24.4,42749,4005,9.4,15.3,-10.7

In [74]:
#All ethinicities lose % from K-5 tp 9-12.  Multi-Racial loses the least, then Black.
#Change s data so can use those columns in calculations.
import numpy as np
cs_schools.replace('s', np.nan, inplace=True)

cs_schools['% Students Taking CS (Citywide) Grades 6-8']=cs_schools['% Students Taking CS (Citywide) Grades 6-8'].astype('float64')
cs_schools.dtypes

Category Type                                   object
Category Values                                 object
# of Students All Grades                         int64
# Students Taking CS All Grades                  int64
% Students Taking CS (Citywide) All Grades     float64
% of All CS, All Grades                        float64
# of Students Grades K-5                         int64
# Students Taking CS Grades K-5                  int64
% Students Taking CS (Citywide) Grades K-5     float64
% of All CS, Grades K-5                        float64
# of Students Grades 6-8                         int64
# Students Taking CS Grades 6-8                 object
% Students Taking CS (Citywide) Grades 6-8     float64
% of All CS, Grades 6-8                         object
# of Students Grades 9-12                        int64
# Students Taking CS Grades 9-12                 int64
% Students Taking CS (Citywide) Grades 9-12    float64
% of All CS, Grades 9-12                       float64
% part 9-12 - % part k-5                       float64
dtype: object

In [90]:
cs_schools['% part 6-8 - % part k-5']=cs_schools['% Students Taking CS (Citywide) Grades 6-8']-cs_schools['% Students Taking CS (Citywide) Grades K-5']
cs1=cs_schools[ethnic_mask].sort_values(by='% part 6-8 - % part k-5')
cs1.iloc[:,[0,1,2,18,19]]

,Category Type,Category Values,# of Students All Grades,% part 9-12 - % part k-5,% part 6-8 - % part k-5
42,Ethnicity,Asian,170661,-11.9,-7.8
46,Ethnicity,Native American,10457,-10.1,-6.2
43,Ethnicity,Black,221735,-6.7,-3.0
45,Ethnicity,Multi-Racial,9468,-5.9,-2.0
44,Ethnicity,Hispanic,395134,-7.1,-0.8
47,Ethnicity,White,152745,-10.7,2.8

In [81]:
#Whites were the only ethnicity to get better participation in 6-8 than K-5.  

cs_schools['% part 9-12 - % part 6-8']=cs_schools['% Students Taking CS (Citywide) Grades 9-12']-cs_schools['% Students Taking CS (Citywide) Grades 6-8']
cs1=cs_schools[ethnic_mask].sort_values(by='% part 9-12 - % part 6-8')
cs1.iloc[:,[0,1,2,18,19,20]]

,Category Type,Category Values,# of Students All Grades,% part 9-12 - % part k-5,% part 6-8 - % part k-5,% part 9-12 - % part 6-8
47,Ethnicity,White,152745,-10.7,2.8,-13.5
44,Ethnicity,Hispanic,395134,-7.1,-0.8,-6.3
42,Ethnicity,Asian,170661,-11.9,-7.8,-4.1
45,Ethnicity,Multi-Racial,9468,-5.9,-2.0,-3.9
46,Ethnicity,Native American,10457,-10.1,-6.2,-3.9
43,Ethnicity,Black,221735,-6.7,-3.0,-3.7

In [83]:
#Whites lost most participation by far between 6-8 and 9-12.  

dis_mask=cs_schools['Category Type']=='Student with Disability Status'
cs_schools[dis_mask].iloc[:,[0,1,2,18,19,20]]

,Category Type,Category Values,# of Students All Grades,% part 9-12 - % part k-5,% part 6-8 - % part k-5,% part 9-12 - % part 6-8
50,Student with Disability Status,Students with Disabilities,204955,-8.7,-1.5,-7.2
51,Student with Disability Status,Students without Disabilities,759018,-8.8,-2.3,-6.5

In [84]:
#Students with disabilities lose less between K-5 and 6-8 but more after that to even out.


econ_mask=cs_schools['Category Type']=='Economic Disadvantaged Status'
cs_schools[econ_mask].iloc[:,[0,1,2,18,19,20]]

,Category Type,Category Values,# of Students All Grades,% part 9-12 - % part k-5,% part 6-8 - % part k-5,% part 9-12 - % part 6-8
38,Economic Disadvantaged Status,Economic Disadvantaged,728807,-7.6,-1.8,-5.8
39,Economic Disadvantaged Status,Non Economic Disadvantaged,235166,-11.8,-2.9,-8.9

In [85]:
#Students that are economically disadvantaged lose less participation, especially from 6-8 to 9-12.

eng_mask=cs_schools['Category Type']=='English Language Learner Status'
cs_schools[eng_mask].iloc[:,[0,1,2,18,19,20]]

,Category Type,Category Values,# of Students All Grades,% part 9-12 - % part k-5,% part 6-8 - % part k-5,% part 9-12 - % part 6-8
40,English Language Learner Status,English Language Learners,154938,-10.5,-3.2,-7.3
41,English Language Learner Status,Non English Language Learners,809035,-8.5,-2.2,-6.3

In [87]:
#English language learners lose slightly more

cs_schools[district_mask].sort_values(by= '# of Students All Grades', ascending=False)

,Category Type,Category Values,# of Students All Grades,# Students Taking CS All Grades,% Students Taking CS (Citywide) All Grades,"% of All CS, All Grades",# of Students Grades K-5,# Students Taking CS Grades K-5,% Students Taking CS (Citywide) Grades K-5,"% of All CS, Grades K-5",...,# Students Taking CS Grades 6-8,% Students Taking CS (Citywide) Grades 6-8,"% of All CS, Grades 6-8",# of Students Grades 9-12,# Students Taking CS Grades 9-12,% Students Taking CS (Citywide) Grades 9-12,"% of All CS, Grades 9-12",% part 9-12 - % part k-5,% part 6-8 - % part k-5,% part 9-12 - % part 6-8
1,District,02,61641,7270,11.8,5.4,17856,2670,15.0,3.5,...,498,6.2,1.6,35783,4102,11.5,15.7,-3.5,-8.8,5.3
30,District,31,59364,12658,21.3,9.4,28177,7095,25.2,9.3,...,"4,017",30.9,12.7,18182,1546,8.5,5.9,-16.7,5.7,-22.4
23,District,24,57548,8871,15.4,6.6,29851,5413,18.1,7.1,...,"2,102",15.7,6.6,14347,1356,9.5,5.2,-8.6,-2.4,-6.2
9,District,10,53991,5435,10.1,4.0,26022,3647,14.0,4.8,...,962,8.2,3.0,16166,826,5.1,3.2,-8.9,-5.8,-3.1
19,District,20,50896,9236,18.1,6.9,25355,6399,25.2,8.3,...,"1,756",14.2,5.5,13202,1081,8.2,4.1,-17.0,-11.0,-6.0
26,District,27,42997,8460,19.7,6.3,21515,6212,28.9,8.1,...,"1,336",12.2,4.2,10519,912,8.7,3.5,-20.2,-16.7,-3.5
27,District,28,40184,7059,17.6,5.2,17235,4361,25.3,5.7,...,"2,093",26.7,6.6,15103,605,4.0,2.3,-21.3,1.4,-22.7
29,District,30,38548,6073,15.8,4.5,18383,3138,17.1,4.1,...,"2,322",23.5,7.3,10292,613,6.0,2.3,-11.1,6.4,-17.5
10,District,11,38391,1661,4.3,1.2,19915,748,3.8,1.0,...,810,8.6,2.6,9043,103,1.1,0.4,-2.7,4.8,-7.5
24,District,25,37139,9563,25.7,7.1,18052,7594,42.1,9.9,...,572,6.7,1.8,10517,1397,13.3,5.4,-28.8,-35.4,6.6
20,District,21,34798,3569,10.3,2.7,13745,867,6.3,1.1,...,"1,566",16.8,4.9,11726,1136,9.7,4.4,3.4,10.5,-7.1
21,District,22,33418,6112,18.3,4.5,16990,2555,15.0,3.3,...,"2,211",34.5,7.0,10015,1346,13.4,5.2,-1.6,19.5,-21.1
8,District,09,33388,2858,8.6,2.1,16884,1590,9.4,2.1,...,705,8.6,2.2,8276,563,6.8,2.2,-2.6,-0.8,-1.8
25,District,26,31600,11069,35.0,8.2,11532,7408,64.2,9.7,...,"2,471",40.5,7.8,13962,1190,8.5,4.6,-55.7,-23.7,-32.0
14,District,15,30697,3827,12.5,2.8,18501,2137,11.6,2.8,...,"1,427",23.7,4.5,6169,263,4.3,1.0,-7.3,12.1,-19.4
7,District,08,27318,1502,5.5,1.1,13214,539,4.1,0.7,...,676,10.6,2.1,7700,287,3.7,1.1,-0.4,6.5,-6.9
32,District,75,26275,1035,3.9,0.8,11321,374,3.3,0.5,...,274,5.4,0.9,9876,387,3.9,1.5,0.6,2.1,-1.5
28,District,29,26026,4247,16.3,3.2,14534,3078,21.2,4.0,...,403,5.8,1.3,4546,766,16.8,2.9,-4.4,-15.4,11.0
11,District,12,22656,628,2.8,0.5,11225,12,0.1,0.0,...,97,1.9,0.3,6331,519,8.2,2.0,8.1,1.8,6.3
2,District,03,21770,1695,7.8,1.3,8508,730,8.6,1.0,...,517,11.9,1.6,8926,448,5.0,1.7,-3.6,3.3,-6.9
18,District,19,21512,2723,12.7,2.0,10819,1399,12.9,1.8,...,"1,068",21.0,3.4,5598,256,4.6,1.0,-8.3,8.1,-16.4
5,District,06,21354,1513,7.1,1.1,10707,756,7.1,1.0,...,573,11.4,1.8,5641,184,3.3,0.7,-3.8,4.3,-8.1
16,District,17,20938,2448,11.7,1.8,8574,1898,22.1,2.5,...,NaN,NaN,NaN,7678,550,7.2,2.1,-14.9,NaN,NaN
12,District,13,20560,3434,16.7,2.6,6756,625,9.3,0.8,...,316,15.1,1.0,11715,2493,21.3,9.5,12.0,5.8,6.2
6,District,07,18401,826,4.5,0.6,7690,24,0.3,0.0,...,293,8.3,0.9,7183,509,7.1,1.9,6.8,8.0,-1.2
13,District,14,17619,2669,15.1,2.0,7543,1742,23.1,2.3,...,343,9.4,1.1,6438,584,9.1,2.2,-14.0,-13.7,-0.3
17,District,18,14766,2630,17.8,2.0,6885,1215,17.6,1.6,...,771,23.1,2.4,4537,644,14.2,2.5,-3.4,5.5,-8.9
3,District,04,12618,866,6.9,0.6,5920,204,3.4,0.3,...,364,12.2,1.1,3716,298,8.0,1.1,4.6,8.8,-4.2
0,District,01,11088,1241,11.2,0.9,5175,347,6.7,0.5,...,310,12.6,1.0,3445,584,17.0,2.2,10.3,5.9,4.4
4,District,05,10791,963,8.9,0.7,4759,574,12.1,0.7,...,185,7.8,0.6,3672,204,5.6,0.8,-6.5,-4.3,-2.2
31,District,32,10662,855,8.0,0.6,5059,223,4.4,0.3,...,456,14.3,1.4,2420,176,7.3,0.7,2.9,9.9,-7.0
22,District,23,8694,498,5.7,0.4,4360,300,6.9,0.4,...,148,5.5,0.5,1655,50,3.0,0.2,-3.9,-1.4,-2.5
15,District,16,6325,1013,16.0,0.8,3209,825,25.7,1.1,...,NaN,NaN,NaN,2110,127,6.0,0.5,-19.7,NaN,NaN

In [1]:
#Size of District does not seem to affect participation

Conclusions:
  In general, most groups lose participation over time.  
  This was true in most Districts.  Possibly there is more interest in younger grades or that 
     there are mandatory classes in K-5 versus elective classes in older grades.
  However in 8 Districts the opposite was true.  (Districts 13, 1 12, 7, 4, 21, 32 and 75.)  I'd be interested in following
     that up to see if maybe there were fewer opportunities in K-5 in those Districts or if they have a successful
     campaign in the older grades to increase interest and/or participation.
  Between boys and girls, both decreased over time. Girls had slightly higher participation in K-5, 
     then lost more from K-5 to 6-9 to have a slightly lower participatin and then 
     lost more to end up with a lower participation in 9-12.
  Students with disability status lost less between K-5 and 6-9 but more between 6-9 and 9-12.
  Ethnic groups also lost participation over time.  Multi-Racial and Black groups lost the least percentage of participation.
     Whites actually increased from K-5 to 6-9 but then lost more by far between 6-9 and 9-12.
  Student with econonmic disadvantaged status lost the least, especially between 6-8 and 9-12.

Pandas skills used:
  read csv file
  information and counts of columns
  rename columns
  clean data, change s to NaN in data
  change column data type
  make new columns using calculations of existing columns
  make masks
  display restricted areas of dataframe
  data analysis